Reland "Add go lints to our presubmits."
This reverts commit 6d756cdeedf8c7c9a66530cf2a97acc6d510fc86.

Reason for revert: Added a custom comparator to the sort to fix the bug.

Original change's description:
> Revert "Add go lints to our presubmits."
>
> This reverts commit 84c39dc66c7d22fd8a38ed3a3dfe3e186c4c014f.
>
> Reason for revert: 
> ```
> ukai@ukai ...infra/build/siso % git cl upload
> Found change with 1 commit...
> Running presubmit upload checks ...
> ** Presubmit ERRORS: 1 **
> Evaluation of CheckChangeOnUpload failed: '<' not supported between instances of 'GitAffectedFile' and 'GitAffectedFile', Traceback (most recent call last):
>   File "/usr/local/google/home/ukai/depot_tools/presubmit_support.py", line 1836, in _run_check_function
>     result = eval(function_name + '(*__args)', context)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<string>", line 1, in <module>
>   File "/usr/local/google/home/ukai/src/infra/infra/PRESUBMIT.py", line 473, in CheckChangeOnUpload
>     output = CommonChecks(input_api, output_api)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/google/home/ukai/src/infra/infra/PRESUBMIT.py", line 428, in CommonChecks
>     output, tests = GoChecks(input_api, output_api)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/google/home/ukai/src/infra/infra/PRESUBMIT.py", line 400, in GoChecks
>     tests = GoCheckers(input_api, output_api)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/google/home/ukai/src/infra/infra/PRESUBMIT.py", line 124, in GoCheckers
>     affected_files = sorted([
>                      ^^^^^^^^
> TypeError: '<' not supported between instances of 'GitAffectedFile' and 'GitAffectedFile'
>
>
> Presubmit checks took 1.3s to calculate.
> There were presubmit errors.
> ```
>
> Original change's description:
> > Add go lints to our presubmits.
> >
> > We run golangci-lint on all changed packages now.
> >
> > Bug: 40944810 
> > Change-Id: Ied2f76c8b561e5e312b080f48208397fdc751fea
> > Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/6038582
> > Auto-Submit: Matt Stark <msta@google.com>
> > Reviewed-by: Philipp Wollermann <philwo@google.com>
> > Commit-Queue: Matt Stark <msta@google.com>
> > Reviewed-by: Junji Watanabe <jwata@google.com>
> > Reviewed-by: Fumitoshi Ukai <ukai@google.com>
> > Cr-Commit-Position: refs/heads/main@{#71041}
>
> Bug: 40944810 
> Change-Id: I0f9f5b3d0f87a32171e6ccaf8acd1cffd4c6a2c8
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/6184875
> Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> Reviewed-by: Matt Stark <msta@google.com>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Reviewed-by: Junji Watanabe <jwata@google.com>
> Cr-Commit-Position: refs/heads/main@{#71045}

Bug: 40944810 
Change-Id: Id48107fbb3409dbaa17365139e907b0dda011d16
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/6186403
Reviewed-by: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Junji Watanabe <jwata@google.com>
Reviewed-by: Philipp Wollermann <philwo@google.com>
Auto-Submit: Matt Stark <msta@google.com>
Reviewed-by: Junji Watanabe <jwata@google.com>
Cr-Commit-Position: refs/heads/main@{#71063}