Revert "siso: Do not download .so with -output_local_strategy=greedy"
This reverts commit bb5e97c8d0463a7451c2a7493b61989ba26525c1.

Reason for revert: .so is also necessary for packaging.

[31680/86669] 47.23s F ACTION //base:base_unittests_pkg__archive-manifest(//build/toolchain/fuchsia:x64)
FAILED: ac98e7dd-59cd-45aa-88c4-50f61a6ecc1b "./gen/base/base_unittests/base_unittests.manifest" ACTION //base:base_unittests_pkg__archive-manifest(//build/toolchain/fuchsia:x64)
err: exit=1
python3 ../../third_party/fuchsia-gn-sdk/src/prepare_package_inputs.py --root-dir ../../ --out-dir . --app-name base_unittests --runtime-deps-file gen/base/base_unittests/base_unittests.runtime_deps --depfile-path gen/base/base_unittests_pkg_stamp.d --manifest-path gen/base/base_unittests/base_unittests.manifest --build-ids-file gen/base/base_unittests/ids.txt --json-file /usr/local/google/home/jwata/chromium/src/out/fuchsia-x64-cast-receiver-rel/gen/base/base_unittests_packaged_components_metadata.json --readelf-exec ../../third_party/llvm-build/Release+Asserts/bin/llvm-readelf --exclude-path third_party/devtools-frontend/src/\* --exclude-path \*.git/\* --exclude-path \*.svn/\* --exclude-path \*.hg/\* --exclude-path third_party/devtools-frontend/src/\*
build step: __base_base_unittests_pkg__archive-manifest___build_toolchain_fuchsia_x64__rule "./gen/base/base_unittests/base_unittests.manifest"
stderr:
Traceback (most recent call last):
  File "/usr/local/google/home/jwata/chromium/src/out/fuchsia-x64-cast-receiver-rel/../../third_party/fuchsia-gn-sdk/src/prepare_package_inputs.py", line 349, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/google/home/jwata/chromium/src/out/fuchsia-x64-cast-receiver-rel/../../third_party/fuchsia-gn-sdk/src/prepare_package_inputs.py", line 345, in main
    return _build_manifest(args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/jwata/chromium/src/out/fuchsia-x64-cast-receiver-rel/../../third_party/fuchsia-gn-sdk/src/prepare_package_inputs.py", line 306, in _build_manifest
    binaries = [f for f in expanded_files if _is_binary(f)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/jwata/chromium/src/out/fuchsia-x64-cast-receiver-rel/../../third_party/fuchsia-gn-sdk/src/prepare_package_inputs.py", line 306, in <listcomp>
    binaries = [f for f in expanded_files if _is_binary(f)]
                                             ^^^^^^^^^^^^^
  File "/usr/local/google/home/jwata/chromium/src/out/fuchsia-x64-cast-receiver-rel/../../third_party/fuchsia-gn-sdk/src/prepare_package_inputs.py", line 68, in _is_binary
    with open(path, 'rb') as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'lib.unstripped/libimmediate_crash_test_helper.so'

Original change's description:
> siso: Do not download .so with -output_local_strategy=greedy
>
> Android, Fuchsia builds use "greedy" download strategy.
> Not downloading .so should give a bit more speedup.
>
> Bug: 370860664
> Change-Id: Ib2a7ba22bd83473e576e906f747c7020502274b1
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/5999873
> Commit-Queue: Junji Watanabe <jwata@google.com>
> Reviewed-by: Fumitoshi Ukai <ukai@google.com>
> Cr-Commit-Position: refs/heads/main@{#69699}

Bug: 370860664
Change-Id: Ic3d3cf50ac73509fc835610d7f57989e9c802088
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/6002631
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Junji Watanabe <jwata@google.com>
Cr-Commit-Position: refs/heads/main@{#69701}