siso: Fix "unknown target" error on Windows
When specifying a `default` target that includes slashes in the
build.ninja file, Siso would fail with an error about this being an
unknown target. For example, editing Chromium's build.ninja file like
this:

```
[...]
default obj/v8/v8_turboshaft/typer.obj
```

results in this error:

```
PS C:\src\chromium\src> autoninja -C out\test
[...]
Error: failed to load build.ninja:
build.ninja:51911 unknown target "obj\\v8\\v8_turboshaft\\typer.obj"
```

However, building the same target directly on the command line works:

```
PS C:\src\chromium\src> autoninja -C out\test `
  obj/v8/v8_turboshaft/typer.obj
```

The reason is that `filepath.Clean` replaces slashes with backslashes
on Windows, but Ninja targets must always use normal slashes, no matter
the current platform.

Change-Id: I9cf235c8354c67518d34f4be221dcd9632c5d3cb
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/5632814
Auto-Submit: Philipp Wollermann <philwo@google.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#66220}